language: objective-c
osx_image: xcode9.1
script:
- set -o pipefail
- bundle exec danger || echo "Danger failed, moving on"
- xcodebuild test -project FontWeather.xcodeproj -scheme FontWeather -destination 'platform=iOS Simulator,name=iPhone 7' | bundle exec xcpretty -c
- xcodebuild -project FontWeather.xcodeproj -scheme FontWeather-watchOS -destination 'OS=4.0,name=Apple Watch - 42mm' | bundle exec xcpretty -c
before_deploy:
  - carthage build --no-skip-current
  - carthage archive FontWeather
