language: objective-c
osx_image: xcode9.1
script:
- xcodebuild test -project FontWeather.xcodeproj -scheme FontWeather -destination 'platform=iOS Simulator,name=iPhone 7' 
- xcodebuild -project FontWeather.xcodeproj -scheme FontWeather-watchOS -destination 'OS=4.0,name=Apple Watch - 42mm' 
before_deploy:
  - carthage build --no-skip-current
  - carthage archive FontWeather
